create table "public"."media" (
    "uid" bigint generated by default as identity not null,
    "plan_id" uuid,
    "url" text,
    "created_at" timestamp with time zone not null default now(),
    "delete_flag" boolean default false,
    "upload_user_id" uuid
);


alter table "public"."media" enable row level security;

alter table "public"."plan" add column "member_id" uuid[] default '{}'::uuid[];

CREATE UNIQUE INDEX media_pkey ON public.media USING btree (uid);

alter table "public"."media" add constraint "media_pkey" PRIMARY KEY using index "media_pkey";

alter table "public"."media" add constraint "media_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES plan(uid) not valid;

alter table "public"."media" validate constraint "media_plan_id_fkey";

alter table "public"."media" add constraint "media_upload_user_id_fkey" FOREIGN KEY (upload_user_id) REFERENCES auth.users(id) not valid;

alter table "public"."media" validate constraint "media_upload_user_id_fkey";

grant delete on table "public"."media" to "anon";

grant insert on table "public"."media" to "anon";

grant references on table "public"."media" to "anon";

grant select on table "public"."media" to "anon";

grant trigger on table "public"."media" to "anon";

grant truncate on table "public"."media" to "anon";

grant update on table "public"."media" to "anon";

grant delete on table "public"."media" to "authenticated";

grant insert on table "public"."media" to "authenticated";

grant references on table "public"."media" to "authenticated";

grant select on table "public"."media" to "authenticated";

grant trigger on table "public"."media" to "authenticated";

grant truncate on table "public"."media" to "authenticated";

grant update on table "public"."media" to "authenticated";

grant delete on table "public"."media" to "service_role";

grant insert on table "public"."media" to "service_role";

grant references on table "public"."media" to "service_role";

grant select on table "public"."media" to "service_role";

grant trigger on table "public"."media" to "service_role";

grant truncate on table "public"."media" to "service_role";

grant update on table "public"."media" to "service_role";

create policy "policy_media"
on "public"."media"
as permissive
for all
to authenticated
using ((EXISTS ( SELECT 1
   FROM plan p
  WHERE ((p.uid = media.plan_id) AND (p.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM plan p
  WHERE ((p.uid = media.plan_id) AND (p.user_id = auth.uid())))));



